### PR TITLE
[ENH]: Add napari framework classifier

### PR DESCRIPTION
**Pull request by sofroniewn**
Hi @hectormz this PR will add a napari framework classifier to the plugin so it will be more easily discoverable, do you mind merging and then making a new release. Thanks!!! Hope all has been well with you :-)

### CODE REVIEW

**Comment by hectormz** [comment]
Thanks @sofroniewn ! I'll merge this PR and upload a new version. I shall return to napari, too!

**Comment by sofroniewn** [comment]
> I shall return to napari, too!

Awesome! Yes, we've made some exciting progress recently. Hope you've been well, it would be great to see you again and catch up!!

**Comment by hectormz** [comment]
Up on PyPI! I always see napari on my twitter feed 😄 I'll try to see if there is a meeting I can drop in on and see what's new! Not sure if the time changed

**Comment by sofroniewn** [comment]
Same time 4pm pacific on thursdays, zoom link should be same too. i can send again in the zulip!

**Pull request merged**
